server:
  port: 8443
  address: 0.0.0.0
spring:
#   application:
#     name: system
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/test_jpa?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:123456}

#hibernate JPA
  jpa:
    database: MYSQL
    #配置是否自动创建数据库表
    generate-ddl: true
    #设置为true：Spring Boot整合JPA后Hibernate的Session就交付给Spring去管理。每次数据库操作后，会关闭Session，当我们想要用懒加载方式去获得数据的时候，原来的Session已经关闭，不能获取数据
    #设置为false：防止hibernate的session外延到controller
    open-in-view: true
    #显示sql语句
    show-sql: true
    hibernate:
    #在springboot项目中使用springdata Jpa，并且希望当我的实体类发生了更改，数据库表结构随着实体类的改变而自动做出相应的改变。  
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #格式化sql
        dialect: org.hibernate.dialect.MySQL5Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        enable_lazy_load_no_trans: true # 开启懒加载,不开启在实体类中使用 FetchType.LAZY 会报错

# 显示jpq的sql参数
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace